# Generated by Django 2.1.5 on 2020-02-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppChatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=10)),
                ('Phone', models.IntegerField(default=None)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Speciality', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'Doctor_Details',
            },
        ),
        migrations.CreateModel(
            name='Hospital_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=None, max_length=100)),
                ('Address', models.CharField(default=None, max_length=100)),
                ('Contact', models.CharField(default=None, max_length=100)),
                ('EmergencyContact', models.CharField(default=None, max_length=100)),
                ('BloodBank', models.CharField(default=None, max_length=100)),
                ('AmbulanceService', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'Hospital_Details',
            },
        ),
    ]
