# Generated by Django 3.0.3 on 2020-03-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppChatbot', '0002_doctor_details_hospital_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MainKeyword', models.CharField(default=None, max_length=200)),
                ('Helping1', models.CharField(default=None, max_length=200)),
                ('Helping2', models.CharField(default=None, max_length=200)),
                ('Helping3', models.CharField(default=None, max_length=200)),
                ('Helping4', models.CharField(default=None, max_length=200)),
                ('Output', models.CharField(default=None, max_length=500)),
            ],
            options={
                'db_table': 'Training_Data',
            },
        ),
    ]
