# Generated by Django 3.0.3 on 2020-03-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppChatbot', '0003_training_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='training_data',
            name='Score',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
