# Generated by Django 3.0.3 on 2020-03-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppChatbot', '0004_training_data_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training_data',
            name='Score',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
